admin_carnet:
    path:     /
    defaults: { _controller: "CarnetsBundle:Carnet:index" }

admin_carnet_new:
    path:     /new
    defaults: { _controller: "CarnetsBundle:Carnet:new" }

admin_carnet_create:
    path:     /create
    defaults: { _controller: "CarnetsBundle:Carnet:create" }
    methods:  POST

admin_carnet_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetsBundle:Carnet:edit" }

admin_carnet_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetsBundle:Carnet:update" }
    methods:  [POST, PUT]

admin_carnet_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetsBundle:Carnet:delete" }
#    methods:  [POST, DELETE]
