admin_lieu:
    path:     /
    defaults: { _controller: "CarnetsBundle:Lieu:index" }

admin_lieu_show:
    path:     /{id}/show
    defaults: { _controller: "CarnetsBundle:Lieu:show" }

admin_lieu_new:
    path:     /new
    defaults: { _controller: "CarnetsBundle:Lieu:new" }

admin_lieu_create:
    path:     /create
    defaults: { _controller: "CarnetsBundle:Lieu:create" }
    methods:  POST

admin_lieu_edit:
    path:     /{id}/edit
    defaults: { _controller: "CarnetsBundle:Lieu:edit" }

admin_lieu_update:
    path:     /{id}/update
    defaults: { _controller: "CarnetsBundle:Lieu:update" }
    methods:  [POST, PUT]

admin_lieu_delete:
    path:     /{id}/delete
    defaults: { _controller: "CarnetsBundle:Lieu:delete" }
    methods:  [POST, DELETE, GET]
